In [173]:
print(confusion_matrix)

[[0.71891892 0.00520833 0.03428571 0.02173913 0.         0.        ]
 [0.01081081 0.65625    0.03428571 0.02717391 0.01282051 0.01851852]
 [0.         0.015625   0.37142857 0.         0.         0.02777778]
 [0.01621622 0.00520833 0.         0.69021739 0.         0.        ]
 [0.01621622 0.03125    0.07428571 0.00543478 0.80128205 0.12037037]
 [0.00540541 0.01041667 0.03428571 0.         0.07051282 0.49074074]
 [0.23243243 0.27604167 0.45142857 0.25543478 0.11538462 0.34259259]]


5(A) The perceptron classifier has the highest accuracy for examples that belong to class 5 with an accuracy of roughly 80%

5(B) The perceptron classifier has the lowest accuracy for examples that belong to class 3 with an accuracy of roughly 37%

5(C):  Perceptron 1 predicts 3 the worst, Perceptron 2 predicts 3 the worst, 3 predicts 1 the worst, 6 predict 5 the worst, 4 predicts 1 the worst, and 5 predicts 6 the worst

In [128]:
import numpy as np

In [129]:
train_data = np.loadtxt('pa3train.txt')
test_data = np.loadtxt('pa3test.txt')
dictionary = np.loadtxt('pa3dictionary.txt',dtype = str)

In [130]:
X_train = train_data[:, :-1]
y_train = train_data[:, -1]
X_test = test_data[:,:-1]
y_test = test_data[:,-1]

In [131]:
print(X_train)
train_data

[[0. 1. 3. ... 0. 0. 0.]
 [0. 0. 3. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]]


array([[0., 1., 3., ..., 0., 0., 5.],
       [0., 0., 3., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 4.],
       ...,
       [0., 0., 0., ..., 0., 0., 6.],
       [0., 0., 2., ..., 0., 0., 1.],
       [0., 0., 2., ..., 0., 0., 5.]])

In [132]:
X_train_1_or_2 = train_data[np.logical_or(y_train ==1, y_train ==2), :-1]
y_train_1_or_2 = train_data[np.logical_or(y_train ==1, y_train ==2), -1]
X_test_1_or_2 = test_data[np.logical_or(y_test==1, y_test==2), :-1]
y_test_1_or_2 = test_data[np.logical_or(y_test==1, y_test==2), -1]
#how to get the subset of indices where label is either 1 or 2


#as the perceptron deals in positives and negatives must convert
#one of the labels to a negative, I have picked y_train = 2 to be converted
size_current_y_train = len(y_train_1_or_2)
size_current_y_test = len(y_test_1_or_2)
for i in range(size_current_y_train):
    if y_train_1_or_2[i] == 2:
        y_train_1_or_2[i] = -1.0
        #make the selected label a negative, perfect to have one pos
        #and one neg for perceptron's binary classifier algorithm
        
for i in range(size_current_y_test):
    if y_test_1_or_2[i] == 2:
        y_test_1_or_2[i] = -1.0

In [133]:
def calculate_linear_error(weights, x,y):
    num_mistakes = 0
    
    predicted = None
    x_size = len(x)
    
    for i in range(x_size):
        if np.dot(weights,x[i]) <0:
            
            predicted = -1
        else:
            
            predicted = 1
            
        if predicted != y[i]:
            #if the predicted label of positive for =1 or negative for
            #equals 2 and the actual label is the opposite, then the linear classification was incorrect 
            num_mistakes +=1
    percent_mistakes = num_mistakes / x_size
    return percent_mistakes

Part 1

In [134]:
train_vec_len = len(X_train_1_or_2[1])
weights  = np.zeros(train_vec_len)
def perceptron_alg(weights,vec,labels):
    vec_size = len(vec)
    for i in range(vec_size):
        if labels[i]*np.dot(weights,vec[i]) <= 0:
            weights = weights +labels[i] *vec[i]
    return weights


In [135]:
w1_output = perceptron_alg(weights, X_train_1_or_2, y_train_1_or_2)
print('The training error after the first pass is: ' + str(calculate_linear_error(w1_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the first pass is: ' + str(calculate_linear_error(w1_output, X_test_1_or_2, y_test_1_or_2)))
print()

w2_output = perceptron_alg(w1_out, X_train_1_or_2, y_train_1_or_2)
print('The training error after the second pass is: ' + str(calculate_linear_error(w2_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the second pass is: ' + str(calculate_linear_error(w2_output, X_test_1_or_2, y_test_1_or_2)))
print()

w3_output = perceptron_alg(w2_out, X_train_1_or_2, y_train_1_or_2)
print('The training error after the third pass is: ' + str(calculate_linear_error(w3_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the third pass is: ' + str(calculate_linear_error(w3_output, X_test_1_or_2, y_test_1_or_2)))
print()

w4_output = perceptron_alg(w3_out, X_train_1_or_2, y_train_1_or_2)
print('The training error after the fourth pass is: '+ str(calculate_linear_error(w4_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the fourth pass is: ' + str(calculate_linear_error(w4_output, X_test_1_or_2, y_test_1_or_2)))
print()

The training error after the first pass is: 0.03853211009174312
The test Error after the first pass is: 0.05305039787798409

The training error after the second pass is: 0.03577981651376147
The test Error after the second pass is: 0.0610079575596817

The training error after the third pass is: 0.01834862385321101
The test Error after the third pass is: 0.04509283819628647

The training error after the fourth pass is: 0.01651376146788991
The test Error after the fourth pass is: 0.04509283819628647



Part 2

In [136]:
train_vec_len = len(X_train_1_or_2[1])
weights = np.zeros(train_vec_len)
def logisticregress(i, weights, vec, labels, lr = .001):
    for iter_count in range(i):

        loss_function = 0
        for i in range(len(vec)):
        
            exponent = labels[i] * np.dot(weights.T, vec[i])
            denominator = 1+ np.exp(exponent)
        
            numerator = vec[i] * labels[i]
        
            loss_function += numerator / denominator
        weights = weights + lr*loss_function
    return weights

In [137]:
iter_10_output = logisticregress(10, weights, X_train_1_or_2, y_train_1_or_2)

iter_50_output = logisticregress(50, weights, X_train_1_or_2, y_train_1_or_2)

iter_100_output = logisticregress(100, weights, X_train_1_or_2, y_train_1_or_2)

iter_2_output = logisticregress(2, weights, X_train_1_or_2, y_train_1_or_2)


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in exp
  # Remove the CWD from sys.path while we load stuff.


In [138]:
print('The Training Error after 10 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_10_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the 10 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_10_output, X_test_1_or_2, y_test_1_or_2)))
print()
print()
print('The Training Error after 50 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_50_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the 50 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_50_output, X_test_1_or_2, y_test_1_or_2)))
print()
print()
print('The Training Error after 100 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_100_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the 100 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_100_output,X_test_1_or_2, y_test_1_or_2)))

print()
print()
print('The Training Error after 2 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_2_output, X_train_1_or_2, y_train_1_or_2)))
print('The test Error after the 2 Iterations of Gradient Descent is: ' + str(calculate_linear_error(iter_2_output, X_test_1_or_2, y_test_1_or_2)))
#According to the PA instructions the code is right if after 2 iterations
#the train error is approximately .497, which is basically what I got

The Training Error after 10 Iterations of Gradient Descent is: 0.2944954128440367
The test Error after the 10 Iterations of Gradient Descent is: 0.29708222811671087


The Training Error after 50 Iterations of Gradient Descent is: 0.03669724770642202
The test Error after the 50 Iterations of Gradient Descent is: 0.0610079575596817


The Training Error after 100 Iterations of Gradient Descent is: 0.01743119266055046
The test Error after the 100 Iterations of Gradient Descent is: 0.04509283819628647


The Training Error after 2 Iterations of Gradient Descent is: 0.4944954128440367
The test Error after the 2 Iterations of Gradient Descent is: 0.4907161803713528


Part 3

In [139]:
sort_w4 = sorted(w4_output)
size_w4_output = len(w4_output)
max_values = set(sort_w4[-3:])
max_val_coord = []

min_values = set(sort_w4[:3])
min_val_coord = []

for i in range(size_w4_output):
    if w4_output[i] in max_values:
        max_val_coord.append(i)
    if w4_output[i] in min_values:
        min_val_coord.append(i)

In [140]:
print('The words that most strongly indicate the positive class are the ')
print(str(max_val_coord[0]) + 'th coordinate, with a value = ' + str(w4_output[max_val_coord[0]]) + ', and the Dictionary Word being:  ' + dictionary[max_val_coord[0]])
print(str(max_val_coord[1]) + 'th coordinate, with a value = ' + str(w4_output[max_val_coord[1]]) + ', and the Dictionary Word being: ' + dictionary[max_val_coord[1]])
print(str(max_val_coord[2]) + 'th coordinate, with a value = ' + str(w4_output[max_val_coord[2]]) + ', and the Dictionary Word being:  ' + dictionary[max_val_coord[2]])
print()
print()

print('The words that most strongly indicate the negative class are the')
print(str(min_val_coord [0]) + 'th coordinate, with a value =' + str(w4_output[min_val_coord[0]]) + ', and the Dictionary Word being:   ' + dictionary[min_val_coord[0]])
print(str(min_val_coord [1]) + 'th coordinate, with a value = ' + str(w4_output[min_val_coord[1]]) + ', and the Dictionary Word being: ' + dictionary[min_val_coord[1]])
print(str(min_val_coord [2]) + 'th coordinate, with a value = ' + str(w4_output[min_val_coord[2]]) + ', and the Dictionary Word being: ' + dictionary[min_val_coord[2]])


The words that most strongly indicate the positive class are the 
203th coordinate, with a value = 45.0, and the Dictionary Word being:  line
438th coordinate, with a value = 130.0, and the Dictionary Word being: file
466th coordinate, with a value = 75.0, and the Dictionary Word being:  program


The words that most strongly indicate the negative class are the
78th coordinate, with a value =-70.0, and the Dictionary Word being:   he
393th coordinate, with a value = -40.0, and the Dictionary Word being: game
469th coordinate, with a value = -43.0, and the Dictionary Word being: team


Part 4

In [141]:
sort_iter_50 = sorted(iter_50_output)
size_iter_50_output = len(iter_50_output)
max_values = set(sort_iter_50[-3:])
max_val_coord = []

min_values = set(sort_iter_50[:3])
min_val_coord = []

for i in range(size_iter_50_output):
    if iter_50_output[i] in max_values:
        max_val_coord.append(i)
    if iter_50_output[i] in min_values:
        min_val_coord.append(i)

In [142]:
print('The words that most strongly indicate the positive class are the ')
print(str(max_val_coord[0]) + 'th coordinate, with a value = ' + str(iter_50_output[max_val_coord[0]]) + ', and the Dictionary Word being:  ' + dictionary[max_val_coord[0]])
print(str(max_val_coord[1]) + 'th coordinate, with a value = ' + str(iter_50_output[max_val_coord[1]]) + ', and the Dictionary Word being: ' + dictionary[max_val_coord[1]])
print(str(max_val_coord[2]) + 'th coordinate, with a value = ' + str(iter_50_output[max_val_coord[2]]) + ', and the Dictionary Word being:  ' + dictionary[max_val_coord[2]])
print()
print()

print('The words that most strongly indicate the negative class are the')
print(str(min_val_coord [0]) + 'th coordinate, with a value =' + str(iter_50_output[min_val_coord[0]]) + ', and the Dictionary Word being:   ' + dictionary[min_val_coord[0]])
print(str(min_val_coord [1]) + 'th coordinate, with a value = ' + str(iter_50_output[min_val_coord[1]]) + ', and the Dictionary Word being: ' + dictionary[min_val_coord[1]])
print(str(min_val_coord [2]) + 'th coordinate, with a value = ' + str(iter_50_output[min_val_coord[2]]) + ', and the Dictionary Word being: ' + dictionary[min_val_coord[2]])

The words that most strongly indicate the positive class are the 
72th coordinate, with a value = 2.049260510216546, and the Dictionary Word being:  use
438th coordinate, with a value = 2.0902558944410456, and the Dictionary Word being: file
617th coordinate, with a value = 3.0424520832865305, and the Dictionary Word being:  window


The words that most strongly indicate the negative class are the
58th coordinate, with a value =-2.182689025614274, and the Dictionary Word being:   they
78th coordinate, with a value = -5.053053106567281, and the Dictionary Word being: he
393th coordinate, with a value = -2.3133631753253874, and the Dictionary Word being: game


Part 5

In [143]:
train_vec_len = len(X_train_1_or_2[1])
weights = np.zeros(train_vec_len)

y_1 = np.copy(y_train)
y_2 = np.copy(y_train)
y_3 = np.copy(y_train)
y_4 = np.copy(y_train)
y_5 = np.copy(y_train)
y_6 = np.copy(y_train)
y_1[y_1 != 1] = -1

y_2[y_2 != 2] = -1
y_2[y_2 == 2] = 1

y_3[y_3 != 3] = -1
y_3[y_3 == 3] = 1

y_4[y_4 != 4] = -1
y_4[y_4 == 4] = 1

y_5[y_5 != 5] = -1
y_5[y_5 == 5] = 1

y_6[y_6 != 6] = -1
y_6[y_6 == 6] = 1

confusion_matrix = np.zeros((7,6))


In [144]:
one_pass_on_all_weights = [perceptron_alg(weights, X_train, y_1), perceptron_alg(weights, X_train, y_2), perceptron_alg(weights, X_train, y_3),
        perceptron_alg(weights, X_train, y_4), perceptron_alg(weights, X_train, y_5), perceptron_alg(weights, X_train, y_6)]
one_pass_on_all_weights

[array([ 31., -10., -10.,  -5., -14.,  -9.,  15., -14.,   4., -12., -20.,
          1.,  -5.,  -7.,   7.,   5.,  18.,  -4.,   5., -14.,  -9.,  16.,
         -2.,   3.,  -2., -17.,  -2.,   4.,   5.,  12.,  18.,   9.,  -9.,
         12., -44.,  -4.,  -7.,  -4.,  -1.,  -3., -11.,  -6.,  -4.,  -3.,
         -1.,  -5.,   6.,  -2.,  -4.,  12.,   1., -14.,  11.,  13.,   8.,
        -10.,  -9.,  -7., -30.,   2.,  -7.,   0., -17.,  -5.,  -8.,  10.,
        -13.,  19.,   0.,  -1.,  12.,   2.,  45.,  -2.,  -7., -15.,  -7.,
         -5., -18., -12.,  -2.,   6., -18., -12.,  -6.,  -4.,  15.,   1.,
          1.,   6., -12.,  -2., -16.,   0., -21., -13.,   1.,  -2.,   0.,
        -16., -11.,  -4.,   9.,  -1.,  -2.,  -1., -10.,  -4.,  -8.,  -5.,
          5.,  -4.,  -5.,  -1.,  -2.,   8., -13.,   4.,  11.,  -4.,  24.,
         -1.,  -3.,   4.,  -6.,  -2.,   1., -15.,  -3.,  -3.,   1.,   0.,
         -2.,  10.,  -5.,  -1.,  -9.,  -3.,   1., -12.,   1., -20.,   3.,
          3.,   6., -29.,  -3.,  -5., 

In [145]:
size_X_test = len(X_test)

size_all_weights = len(one_pass_on_all_weights)
for i in range(size_X_test):
    total_predicts = np.zeros(size_all_weights)
    
    for w in range(size_all_weights):
        
        
        if np.dot(one_pass_on_all_weights[w], X_test[i]) > 0:
            total_predicts[w] = 1
            #binary decider like perceptron
        else:
            total_predicts[w] = -1
    if (np.mean(total_predicts == 1)) != (1/6):
        #in this case, the dont know clause is used, as the prediction is succesful
        #only as long as a single value is positive and all the rest are negative
        #in the event that there's more than 1 positive we can't be certain that a
        #prediction should be made
        predicted_index =6 #where to put values with an i dont know result, the 7th row
    else:
        predicted_index = np.where(total_predicts ==1)[0][0]
        #in this case, index is stored when only a single positive value is
        #reached 
    confusion_matrix[predicted_index, int(y_test[i] -1)] += (1/np.sum(y_test == y_test[i]))
#have to put int with (y_test[i]-1) or else t's invalid indices

In [146]:
print(confusion_matrix)

[[0.71891892 0.00520833 0.03428571 0.02173913 0.         0.        ]
 [0.01081081 0.65625    0.03428571 0.02717391 0.01282051 0.01851852]
 [0.         0.015625   0.37142857 0.         0.         0.02777778]
 [0.01621622 0.00520833 0.         0.69021739 0.         0.        ]
 [0.01621622 0.03125    0.07428571 0.00543478 0.80128205 0.12037037]
 [0.00540541 0.01041667 0.03428571 0.         0.07051282 0.49074074]
 [0.23243243 0.27604167 0.45142857 0.25543478 0.11538462 0.34259259]]


In [164]:

for i in range(6):
    print('The average percent success for each class is '+ str(np.mean(confusion_matrix[i])*100))

#Because we don't count the don't know row which is row 7 or index 6

The average percent success for each class is 13.002534949545783
The average percent success for each class is 12.66432449131725
The average percent success for each class is 6.91385582010583
The average percent success for each class is 11.86069901423165
The average percent success for each class is 17.480652246050767
The average percent success for each class is 10.189355793522452


TypeError: object of type 'numpy.float64' has no len()